### ISSUE TITLE
Flathub package

### ISSUE THREAD

**Issue by flabbet** [PixiEditor/PixiEditor#772]

**Comment by egasimus** [comment]
Way to go! Kindly chiming in to say how happy seeing Pixi on Flathub would make me 😁 A lot!

(I run one of them weirder distros - also because it makes me happy, but sometimes it can be frustrating too; AppImage and especially Flatpak can be absolute lifesavers.)

**Comment by Jack-Sibley** [comment]
As a proof of concept, and in case it's any help, I was able to get a flatpak to build with the following manifest:

```yaml
id: net.pixieditor.PixiEditor
runtime: org.freedesktop.Platform
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.dotnet8
build-options:
  prepend-path: "/usr/lib/sdk/dotnet8/bin"
  append-ld-library-path: "/usr/lib/sdk/dotnet8/lib"
  prepend-pkg-config-path: "/usr/lib/sdk/dotnet8/lib/pkgconfig"
  build-args:
    - --share=network

command: PixiEditor.Desktop

finish-args:
  - --device=dri
  - --socket=x11
  - --share=ipc
  - --env=DOTNET_ROOT=/app/lib/dotnet

modules:
  - name: dotnet
    buildsystem: simple
    build-commands:
    - /usr/lib/sdk/dotnet8/bin/install.sh

  - name: binary
    buildsystem: simple
    sources:
      - type: archive
        url: https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-27/wasi-sdk-27.0-x86_64-linux.tar.gz
        sha256: b7d4d944c88503e4f21d84af07ac293e3440b1b6210bfd7fe78e0afd92c23bc2
      - type: git
        url: https://github.com/PixiEditor/PixiEditor.git
        commit: d490cbdc28626f54bd823550fef32a6d99ecd388
        dest: 'PixiEditor'
    build-commands:
      - export WASI_SDK_PATH="$(realpath wasi-sdk-27.0-x86_64-linux)"
      - dotnet publish PixiEditor/src/PixiEditor.Desktop/PixiEditor.Desktop.csproj -r linux-x64 -c Release --no-self-contained -o publish
      - mkdir -p ${FLATPAK_DEST}/bin
      - cp -r publish/* ${FLATPAK_DEST}/bin
```
